#!/usr/bin/env bash
set -euxo pipefail

#MISE description="build and run the server in a docker container"
#MISE alias="scup"

if command -v docker-compose &>/dev/null; then
  docker-compose up server --build -d
elif command -v docker compose &>/dev/null; then
  docker compose up server --build -d
else
  echo "could not find docker-compose nor docker compose in PATH"
fi
