#!/usr/bin/env bash
set -euxo pipefail

#MISE description="tear down the running server container"
#MISE alias="scdown"

if command -v docker-compose &>/dev/null; then
  docker-compose down server
elif command -v docker compose &>/dev/null; then
  docker compose down server
else
  echo "could not find docker-compose nor docker compose in PATH"
fi
