#!/usr/bin/env bash
set -exo pipefail

#MISE description="invoke server endpoints using grpcurl endpoints"
#MISE alias="curl"
#USAGE arg "<method>" help="the server method to invoke"
#USAGE arg "[request]" help="json body of the request"

if [[ -z "${usage_request}" ]]; then
  grpcurl -plaintext localhost:3000 cardwatcher.v1.CardWatcherService/"${usage_method:?}"
else
  grpcurl -d "${usage_request?}" -plaintext localhost:3000 cardwatcher.v1.CardWatcherService/"${usage_method:?}"
fi
