version: "2"
linters:
  enable:
    - sloglint
  settings:
    sloglint:
      no-global: "all"
      static-msg: true
      attr-only: true
      msg-style: "lowercased"
      key-naming-case: "camel"
      args-on-sep-lines: true
      forbidden-keys:
        - "time"
        - "level"
        - "msg"
        - "source"
