assert_lefthook_installed: true
pre-commit:
  parallel: true
  commands:
    golangci-lint:
      run: golangci-lint run --fast --fix --new-from-rev HEAD~1
      stage_fixed: true
      glob: "*.go"
      exclude:
        - gen/go/*.go
    golangci-fmt:
      run: |
        git diff --name-only --cached -- '*.go' | xargs -r gofumpt -w 
        git diff --name-only --cached -- '*.go' | xargs -r goimports -w
      stage_fixed: true
      glob: "*.go"
    buf-lint:
      run: buf lint
      glob: "*.proto"
      stage_fixed: true
    buf_format:
      run: buf format
      glob: "*.proto"
      stage_fixed: true
