services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    environment:
      APP_ENV: ${APP_ENV}
      PORT: ${PORT}
      MONGO_HOST: mongo
      MONGO_PORT: ${MONGO_PORT}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DATABASE: ${MONGO_DATABASE}
      CARDTRADER_ACCESS_TOKEN: ${CARDTRADER_ACCESS_TOKEN}
      CARDTRADER_API_BASE_URL: ${CARDTRADER_API_BASE_URL}
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - watcher_network
  mongo:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_volume:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - watcher_network

volumes:
  mongo_volume:
networks:
  watcher_network:
