[tools]
docker-compose = "latest"
go = "1.24"
"go:github.com/air-verse/air" = "v1.62"
"go:github.com/melkeydev/go-blueprint" = "0.10"
"go:github.com/fullstorydev/grpcurl/cmd/grpcurl" = "1.9.2"
"go:gotest.tools/gotestsum" = "v1.12.2"
protoc-gen-go = "latest"
protoc-gen-go-grpc = "latest"
"cargo:fblog" = "latest"
"cargo:https://github.com/pamburus/hl.git" = "latest"
"go:github.com/aurc/loggo" = "latest"

[env]
APP_ENV = "DEV"
PORT = 3000
NOTIFICATION_SCHEDULE = "* * * * *"

[tasks.generate]
description = "generate code from protobuf files"
run = "protoc -I=card-watcher-models --go_out ./ card-watcher-models/cardwatcher/* --go-grpc_out ./"
alias = "g"

[tasks.build]
description = "build the app"
run = "go build -o main cmd/api/main.go"
alias = "b"

[tasks.run]
description = "run the app"
run = "go run cmd/api/main.go"
alias = "r"

[tasks.updb]
description = "starts database container"
run = "docker-compose up -d mongo"

[tasks.down]
description = "stops supporting containers"
run = "docker-compose down"

[tasks.test]
description = "run tests"
run = "gotestsum ./... -v"
alias = "t"

[tasks.clean]
description = "cleans artifacts produced"
run = "rm -f main"
alias = "c"

[tasks.watch]
description = "build and run the app watching for changes"
run = "air | hl"
alias = "w"
