[tools]
go = "1.25.7"
docker-compose = "latest"
"go:github.com/air-verse/air" = "v1.62"
"go:github.com/fullstorydev/grpcurl/cmd/grpcurl" = "1.9.2"
"go:gotest.tools/gotestsum" = "v1.12.2"
buf = "1.65"
"cargo:https://github.com/pamburus/hl.git" = "latest"
"go:github.com/aurc/loggo" = "latest"
gh = "2.80.0"
"go:github.com/unkn0wn-root/resterm/cmd/resterm" = "v0.19.1"
golangci-lint = "v2.8.0"
act = "0.2.84"
lefthook = "v2.0.15"
watchexec = "2.5.0"
gofumpt = "v0.9.2"
"go:golang.org/x/tools/cmd/goimports" = "0.42.0"

[env]
LOG_LEVEL = "debug"
SERVER_PORT = 3000
SERVER_HOST = "localhost"
GATEWAY_PORT = 8081
MONGO_PORT = 27017
NTFY_PORT = 80
MONGO_DATABASE = "cardwatcher"
CARDTRADER_API_BASE_URL = "https://api.cardtrader.com/api/v2"
NOTIFICATION_SCHEDULE = "* * * * *"
UPDATE_MAPS_SCHEDULE = "0 4 * * *"
MONGO_WATCH_COLLECTION_NAME = "watches"
SERVER_HEALTH_CHECK_INTERVAL_MILLISECONDS = 1000
SERVER_ENABLE_REFLECTION = true

[settings]
lockfile = true
