// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: responses.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListExpansionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expansions    []*Expansion           `protobuf:"bytes,1,rep,name=expansions,proto3" json:"expansions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExpansionsResponse) Reset() {
	*x = ListExpansionsResponse{}
	mi := &file_responses_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExpansionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExpansionsResponse) ProtoMessage() {}

func (x *ListExpansionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_responses_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExpansionsResponse.ProtoReflect.Descriptor instead.
func (*ListExpansionsResponse) Descriptor() ([]byte, []int) {
	return file_responses_proto_rawDescGZIP(), []int{0}
}

func (x *ListExpansionsResponse) GetExpansions() []*Expansion {
	if x != nil {
		return x.Expansions
	}
	return nil
}

type ListBlueprintsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blueprints    []*Blueprint           `protobuf:"bytes,1,rep,name=blueprints,proto3" json:"blueprints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlueprintsResponse) Reset() {
	*x = ListBlueprintsResponse{}
	mi := &file_responses_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlueprintsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlueprintsResponse) ProtoMessage() {}

func (x *ListBlueprintsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_responses_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlueprintsResponse.ProtoReflect.Descriptor instead.
func (*ListBlueprintsResponse) Descriptor() ([]byte, []int) {
	return file_responses_proto_rawDescGZIP(), []int{1}
}

func (x *ListBlueprintsResponse) GetBlueprints() []*Blueprint {
	if x != nil {
		return x.Blueprints
	}
	return nil
}

type SaveWatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WatchId       string                 `protobuf:"bytes,1,opt,name=watch_id,json=watchId,proto3" json:"watch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveWatchResponse) Reset() {
	*x = SaveWatchResponse{}
	mi := &file_responses_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveWatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveWatchResponse) ProtoMessage() {}

func (x *SaveWatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_responses_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveWatchResponse.ProtoReflect.Descriptor instead.
func (*SaveWatchResponse) Descriptor() ([]byte, []int) {
	return file_responses_proto_rawDescGZIP(), []int{2}
}

func (x *SaveWatchResponse) GetWatchId() string {
	if x != nil {
		return x.WatchId
	}
	return ""
}

type ListWatchesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Watches       []*Watch               `protobuf:"bytes,1,rep,name=watches,proto3" json:"watches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWatchesResponse) Reset() {
	*x = ListWatchesResponse{}
	mi := &file_responses_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWatchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWatchesResponse) ProtoMessage() {}

func (x *ListWatchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_responses_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWatchesResponse.ProtoReflect.Descriptor instead.
func (*ListWatchesResponse) Descriptor() ([]byte, []int) {
	return file_responses_proto_rawDescGZIP(), []int{3}
}

func (x *ListWatchesResponse) GetWatches() []*Watch {
	if x != nil {
		return x.Watches
	}
	return nil
}

var File_responses_proto protoreflect.FileDescriptor

const file_responses_proto_rawDesc = "" +
	"\n" +
	"\x0fresponses.proto\x12\x0ecardwatcher.v1\x1a\x0eentities.proto\"S\n" +
	"\x16ListExpansionsResponse\x129\n" +
	"\n" +
	"expansions\x18\x01 \x03(\v2\x19.cardwatcher.v1.ExpansionR\n" +
	"expansions\"S\n" +
	"\x16ListBlueprintsResponse\x129\n" +
	"\n" +
	"blueprints\x18\x01 \x03(\v2\x19.cardwatcher.v1.BlueprintR\n" +
	"blueprints\".\n" +
	"\x11SaveWatchResponse\x12\x19\n" +
	"\bwatch_id\x18\x01 \x01(\tR\awatchId\"F\n" +
	"\x13ListWatchesResponse\x12/\n" +
	"\awatches\x18\x01 \x03(\v2\x15.cardwatcher.v1.WatchR\awatchesB0Z.github.com/lcampit/cardwatcher/internal/api/v1b\x06proto3"

var (
	file_responses_proto_rawDescOnce sync.Once
	file_responses_proto_rawDescData []byte
)

func file_responses_proto_rawDescGZIP() []byte {
	file_responses_proto_rawDescOnce.Do(func() {
		file_responses_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_responses_proto_rawDesc), len(file_responses_proto_rawDesc)))
	})
	return file_responses_proto_rawDescData
}

var file_responses_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_responses_proto_goTypes = []any{
	(*ListExpansionsResponse)(nil), // 0: cardwatcher.v1.ListExpansionsResponse
	(*ListBlueprintsResponse)(nil), // 1: cardwatcher.v1.ListBlueprintsResponse
	(*SaveWatchResponse)(nil),      // 2: cardwatcher.v1.SaveWatchResponse
	(*ListWatchesResponse)(nil),    // 3: cardwatcher.v1.ListWatchesResponse
	(*Expansion)(nil),              // 4: cardwatcher.v1.Expansion
	(*Blueprint)(nil),              // 5: cardwatcher.v1.Blueprint
	(*Watch)(nil),                  // 6: cardwatcher.v1.Watch
}
var file_responses_proto_depIdxs = []int32{
	4, // 0: cardwatcher.v1.ListExpansionsResponse.expansions:type_name -> cardwatcher.v1.Expansion
	5, // 1: cardwatcher.v1.ListBlueprintsResponse.blueprints:type_name -> cardwatcher.v1.Blueprint
	6, // 2: cardwatcher.v1.ListWatchesResponse.watches:type_name -> cardwatcher.v1.Watch
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_responses_proto_init() }
func file_responses_proto_init() {
	if File_responses_proto != nil {
		return
	}
	file_entities_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_responses_proto_rawDesc), len(file_responses_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_responses_proto_goTypes,
		DependencyIndexes: file_responses_proto_depIdxs,
		MessageInfos:      file_responses_proto_msgTypes,
	}.Build()
	File_responses_proto = out.File
	file_responses_proto_goTypes = nil
	file_responses_proto_depIdxs = nil
}
