// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\x0ecardwatcher.v1\x1a\x0erequests.proto\x1a\x0fresponses.proto\x1a\x1bgoogle/protobuf/empty.proto2\xc0\x03\n" +
	"\vCardWatcher\x12_\n" +
	"\x0eListExpansions\x12%.cardwatcher.v1.ListExpansionsRequest\x1a&.cardwatcher.v1.ListExpansionsResponse\x12_\n" +
	"\x0eListBlueprints\x12%.cardwatcher.v1.ListBlueprintsRequest\x1a&.cardwatcher.v1.ListBlueprintsResponse\x12P\n" +
	"\tSaveWatch\x12 .cardwatcher.v1.SaveWatchRequest\x1a!.cardwatcher.v1.SaveWatchResponse\x12J\n" +
	"\vListWatches\x12\x16.google.protobuf.Empty\x1a#.cardwatcher.v1.ListWatchesResponse\x12Q\n" +
	"\x0fDeleteWatchByID\x12&.cardwatcher.v1.DeleteWatchByIDRequest\x1a\x16.google.protobuf.EmptyB0Z.github.com/lcampit/cardwatcher/internal/api/v1b\x06proto3"

var file_service_proto_goTypes = []any{
	(*ListExpansionsRequest)(nil),  // 0: cardwatcher.v1.ListExpansionsRequest
	(*ListBlueprintsRequest)(nil),  // 1: cardwatcher.v1.ListBlueprintsRequest
	(*SaveWatchRequest)(nil),       // 2: cardwatcher.v1.SaveWatchRequest
	(*emptypb.Empty)(nil),          // 3: google.protobuf.Empty
	(*DeleteWatchByIDRequest)(nil), // 4: cardwatcher.v1.DeleteWatchByIDRequest
	(*ListExpansionsResponse)(nil), // 5: cardwatcher.v1.ListExpansionsResponse
	(*ListBlueprintsResponse)(nil), // 6: cardwatcher.v1.ListBlueprintsResponse
	(*SaveWatchResponse)(nil),      // 7: cardwatcher.v1.SaveWatchResponse
	(*ListWatchesResponse)(nil),    // 8: cardwatcher.v1.ListWatchesResponse
}
var file_service_proto_depIdxs = []int32{
	0, // 0: cardwatcher.v1.CardWatcher.ListExpansions:input_type -> cardwatcher.v1.ListExpansionsRequest
	1, // 1: cardwatcher.v1.CardWatcher.ListBlueprints:input_type -> cardwatcher.v1.ListBlueprintsRequest
	2, // 2: cardwatcher.v1.CardWatcher.SaveWatch:input_type -> cardwatcher.v1.SaveWatchRequest
	3, // 3: cardwatcher.v1.CardWatcher.ListWatches:input_type -> google.protobuf.Empty
	4, // 4: cardwatcher.v1.CardWatcher.DeleteWatchByID:input_type -> cardwatcher.v1.DeleteWatchByIDRequest
	5, // 5: cardwatcher.v1.CardWatcher.ListExpansions:output_type -> cardwatcher.v1.ListExpansionsResponse
	6, // 6: cardwatcher.v1.CardWatcher.ListBlueprints:output_type -> cardwatcher.v1.ListBlueprintsResponse
	7, // 7: cardwatcher.v1.CardWatcher.SaveWatch:output_type -> cardwatcher.v1.SaveWatchResponse
	8, // 8: cardwatcher.v1.CardWatcher.ListWatches:output_type -> cardwatcher.v1.ListWatchesResponse
	3, // 9: cardwatcher.v1.CardWatcher.DeleteWatchByID:output_type -> google.protobuf.Empty
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_requests_proto_init()
	file_responses_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
