#!/usr/bin/env bash

#MISE description="clean artifacts produced and stops containers"
#MISE alias="c"

rm -rf tmp
rm -rf bin
if command -v docker-compose &>/dev/null; then
  docker-compose down
elif command -v docker compose &>/dev/null; then
  docker compose down
else
  echo "could not find docker-compose nor docker compose in PATH"
fi
