#!/usr/bin/env bash

#MISE description="stops all containers running"

if command -v docker-compose &>/dev/null; then
  docker-compose down
elif command -v docker compose &>/dev/null; then
  docker compose down
else
  echo "could not find docker-compose nor docker compose in PATH"
fi
