#!/usr/bin/env bash

#MISE description="generate code from protobuf files"
#MISE alias="g"

protoc \
  --proto_path=proto \
  --go_out=internal/api/v1 \
  --go_opt=paths=source_relative \
  --go-grpc_out=internal/api/v1 \
  --go-grpc_opt=paths=source_relative \
  proto/*.proto
