// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: cardwatcher/entities.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Condition int32

const (
	Condition_CONDITION_UNSPECIFIED       Condition = 0
	Condition_CONDITION_NEAR_MINT         Condition = 1
	Condition_CONDITION_SLIGHTLY_PLAYED   Condition = 2
	Condition_CONDITION_MODERATELY_PLAYED Condition = 3
	Condition_CONDITION_PLAYED            Condition = 4
	Condition_CONDITION_POOR              Condition = 5
)

// Enum value maps for Condition.
var (
	Condition_name = map[int32]string{
		0: "CONDITION_UNSPECIFIED",
		1: "CONDITION_NEAR_MINT",
		2: "CONDITION_SLIGHTLY_PLAYED",
		3: "CONDITION_MODERATELY_PLAYED",
		4: "CONDITION_PLAYED",
		5: "CONDITION_POOR",
	}
	Condition_value = map[string]int32{
		"CONDITION_UNSPECIFIED":       0,
		"CONDITION_NEAR_MINT":         1,
		"CONDITION_SLIGHTLY_PLAYED":   2,
		"CONDITION_MODERATELY_PLAYED": 3,
		"CONDITION_PLAYED":            4,
		"CONDITION_POOR":              5,
	}
)

func (x Condition) Enum() *Condition {
	p := new(Condition)
	*p = x
	return p
}

func (x Condition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Condition) Descriptor() protoreflect.EnumDescriptor {
	return file_cardwatcher_entities_proto_enumTypes[0].Descriptor()
}

func (Condition) Type() protoreflect.EnumType {
	return &file_cardwatcher_entities_proto_enumTypes[0]
}

func (x Condition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Condition.Descriptor instead.
func (Condition) EnumDescriptor() ([]byte, []int) {
	return file_cardwatcher_entities_proto_rawDescGZIP(), []int{0}
}

var File_cardwatcher_entities_proto protoreflect.FileDescriptor

const file_cardwatcher_entities_proto_rawDesc = "" +
	"\n" +
	"\x1acardwatcher/entities.proto\x12\vcardwatcher*\xa9\x01\n" +
	"\tCondition\x12\x19\n" +
	"\x15CONDITION_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13CONDITION_NEAR_MINT\x10\x01\x12\x1d\n" +
	"\x19CONDITION_SLIGHTLY_PLAYED\x10\x02\x12\x1f\n" +
	"\x1bCONDITION_MODERATELY_PLAYED\x10\x03\x12\x14\n" +
	"\x10CONDITION_PLAYED\x10\x04\x12\x12\n" +
	"\x0eCONDITION_POOR\x10\x05B\x11Z\x0finternal/modelsb\x06proto3"

var (
	file_cardwatcher_entities_proto_rawDescOnce sync.Once
	file_cardwatcher_entities_proto_rawDescData []byte
)

func file_cardwatcher_entities_proto_rawDescGZIP() []byte {
	file_cardwatcher_entities_proto_rawDescOnce.Do(func() {
		file_cardwatcher_entities_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cardwatcher_entities_proto_rawDesc), len(file_cardwatcher_entities_proto_rawDesc)))
	})
	return file_cardwatcher_entities_proto_rawDescData
}

var file_cardwatcher_entities_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cardwatcher_entities_proto_goTypes = []any{
	(Condition)(0), // 0: cardwatcher.Condition
}
var file_cardwatcher_entities_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cardwatcher_entities_proto_init() }
func file_cardwatcher_entities_proto_init() {
	if File_cardwatcher_entities_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cardwatcher_entities_proto_rawDesc), len(file_cardwatcher_entities_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cardwatcher_entities_proto_goTypes,
		DependencyIndexes: file_cardwatcher_entities_proto_depIdxs,
		EnumInfos:         file_cardwatcher_entities_proto_enumTypes,
	}.Build()
	File_cardwatcher_entities_proto = out.File
	file_cardwatcher_entities_proto_goTypes = nil
	file_cardwatcher_entities_proto_depIdxs = nil
}
