// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: cardwatcher/requests.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaveWatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpansionId   int32                  `protobuf:"varint,2,opt,name=expansion_id,json=expansionId,proto3" json:"expansion_id,omitempty"`
	BlueprintId   int32                  `protobuf:"varint,3,opt,name=blueprint_id,json=blueprintId,proto3" json:"blueprint_id,omitempty"`
	Condition     Condition              `protobuf:"varint,4,opt,name=condition,proto3,enum=cardwatcher.Condition" json:"condition,omitempty"`
	Foil          bool                   `protobuf:"varint,5,opt,name=foil,proto3" json:"foil,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveWatchRequest) Reset() {
	*x = SaveWatchRequest{}
	mi := &file_cardwatcher_requests_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveWatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveWatchRequest) ProtoMessage() {}

func (x *SaveWatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cardwatcher_requests_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveWatchRequest.ProtoReflect.Descriptor instead.
func (*SaveWatchRequest) Descriptor() ([]byte, []int) {
	return file_cardwatcher_requests_proto_rawDescGZIP(), []int{0}
}

func (x *SaveWatchRequest) GetExpansionId() int32 {
	if x != nil {
		return x.ExpansionId
	}
	return 0
}

func (x *SaveWatchRequest) GetBlueprintId() int32 {
	if x != nil {
		return x.BlueprintId
	}
	return 0
}

func (x *SaveWatchRequest) GetCondition() Condition {
	if x != nil {
		return x.Condition
	}
	return Condition_CONDITION_UNSPECIFIED
}

func (x *SaveWatchRequest) GetFoil() bool {
	if x != nil {
		return x.Foil
	}
	return false
}

var File_cardwatcher_requests_proto protoreflect.FileDescriptor

const file_cardwatcher_requests_proto_rawDesc = "" +
	"\n" +
	"\x1acardwatcher/requests.proto\x12\vcardwatcher\x1a\x1acardwatcher/entities.proto\"\xa2\x01\n" +
	"\x10SaveWatchRequest\x12!\n" +
	"\fexpansion_id\x18\x02 \x01(\x05R\vexpansionId\x12!\n" +
	"\fblueprint_id\x18\x03 \x01(\x05R\vblueprintId\x124\n" +
	"\tcondition\x18\x04 \x01(\x0e2\x16.cardwatcher.ConditionR\tcondition\x12\x12\n" +
	"\x04foil\x18\x05 \x01(\bR\x04foilB\x11Z\x0finternal/modelsb\x06proto3"

var (
	file_cardwatcher_requests_proto_rawDescOnce sync.Once
	file_cardwatcher_requests_proto_rawDescData []byte
)

func file_cardwatcher_requests_proto_rawDescGZIP() []byte {
	file_cardwatcher_requests_proto_rawDescOnce.Do(func() {
		file_cardwatcher_requests_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cardwatcher_requests_proto_rawDesc), len(file_cardwatcher_requests_proto_rawDesc)))
	})
	return file_cardwatcher_requests_proto_rawDescData
}

var file_cardwatcher_requests_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cardwatcher_requests_proto_goTypes = []any{
	(*SaveWatchRequest)(nil), // 0: cardwatcher.SaveWatchRequest
	(Condition)(0),           // 1: cardwatcher.Condition
}
var file_cardwatcher_requests_proto_depIdxs = []int32{
	1, // 0: cardwatcher.SaveWatchRequest.condition:type_name -> cardwatcher.Condition
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cardwatcher_requests_proto_init() }
func file_cardwatcher_requests_proto_init() {
	if File_cardwatcher_requests_proto != nil {
		return
	}
	file_cardwatcher_entities_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cardwatcher_requests_proto_rawDesc), len(file_cardwatcher_requests_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cardwatcher_requests_proto_goTypes,
		DependencyIndexes: file_cardwatcher_requests_proto_depIdxs,
		MessageInfos:      file_cardwatcher_requests_proto_msgTypes,
	}.Build()
	File_cardwatcher_requests_proto = out.File
	file_cardwatcher_requests_proto_goTypes = nil
	file_cardwatcher_requests_proto_depIdxs = nil
}
