// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: cardwatcher/service.proto

package models

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CardWatcher_SaveWatch_FullMethodName = "/cardwatcher.CardWatcher/SaveWatch"
)

// CardWatcherClient is the client API for CardWatcher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CardWatcherClient interface {
	SaveWatch(ctx context.Context, in *SaveWatchRequest, opts ...grpc.CallOption) (*SaveWatchResponse, error)
}

type cardWatcherClient struct {
	cc grpc.ClientConnInterface
}

func NewCardWatcherClient(cc grpc.ClientConnInterface) CardWatcherClient {
	return &cardWatcherClient{cc}
}

func (c *cardWatcherClient) SaveWatch(ctx context.Context, in *SaveWatchRequest, opts ...grpc.CallOption) (*SaveWatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveWatchResponse)
	err := c.cc.Invoke(ctx, CardWatcher_SaveWatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CardWatcherServer is the server API for CardWatcher service.
// All implementations must embed UnimplementedCardWatcherServer
// for forward compatibility.
type CardWatcherServer interface {
	SaveWatch(context.Context, *SaveWatchRequest) (*SaveWatchResponse, error)
	mustEmbedUnimplementedCardWatcherServer()
}

// UnimplementedCardWatcherServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCardWatcherServer struct{}

func (UnimplementedCardWatcherServer) SaveWatch(context.Context, *SaveWatchRequest) (*SaveWatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveWatch not implemented")
}
func (UnimplementedCardWatcherServer) mustEmbedUnimplementedCardWatcherServer() {}
func (UnimplementedCardWatcherServer) testEmbeddedByValue()                     {}

// UnsafeCardWatcherServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CardWatcherServer will
// result in compilation errors.
type UnsafeCardWatcherServer interface {
	mustEmbedUnimplementedCardWatcherServer()
}

func RegisterCardWatcherServer(s grpc.ServiceRegistrar, srv CardWatcherServer) {
	// If the following call pancis, it indicates UnimplementedCardWatcherServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CardWatcher_ServiceDesc, srv)
}

func _CardWatcher_SaveWatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveWatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardWatcherServer).SaveWatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardWatcher_SaveWatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardWatcherServer).SaveWatch(ctx, req.(*SaveWatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CardWatcher_ServiceDesc is the grpc.ServiceDesc for CardWatcher service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CardWatcher_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cardwatcher.CardWatcher",
	HandlerType: (*CardWatcherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveWatch",
			Handler:    _CardWatcher_SaveWatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cardwatcher/service.proto",
}
