// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: cardwatcher/service.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_cardwatcher_service_proto protoreflect.FileDescriptor

const file_cardwatcher_service_proto_rawDesc = "" +
	"\n" +
	"\x19cardwatcher/service.proto\x12\vcardwatcher\x1a\x1acardwatcher/requests.proto\x1a\x1bcardwatcher/responses.proto\x1a\x1bgoogle/protobuf/empty.proto2\xa8\x03\n" +
	"\vCardWatcher\x12Y\n" +
	"\x0eListExpansions\x12\".cardwatcher.ListExpansionsRequest\x1a#.cardwatcher.ListExpansionsResponse\x12Y\n" +
	"\x0eListBlueprints\x12\".cardwatcher.ListBlueprintsRequest\x1a#.cardwatcher.ListBlueprintsResponse\x12J\n" +
	"\tSaveWatch\x12\x1d.cardwatcher.SaveWatchRequest\x1a\x1e.cardwatcher.SaveWatchResponse\x12G\n" +
	"\vListWatches\x12\x16.google.protobuf.Empty\x1a .cardwatcher.ListWatchesResponse\x12N\n" +
	"\x0fDeleteWatchByID\x12#.cardwatcher.DeleteWatchByIDRequest\x1a\x16.google.protobuf.EmptyB\x11Z\x0finternal/modelsb\x06proto3"

var file_cardwatcher_service_proto_goTypes = []any{
	(*ListExpansionsRequest)(nil),  // 0: cardwatcher.ListExpansionsRequest
	(*ListBlueprintsRequest)(nil),  // 1: cardwatcher.ListBlueprintsRequest
	(*SaveWatchRequest)(nil),       // 2: cardwatcher.SaveWatchRequest
	(*emptypb.Empty)(nil),          // 3: google.protobuf.Empty
	(*DeleteWatchByIDRequest)(nil), // 4: cardwatcher.DeleteWatchByIDRequest
	(*ListExpansionsResponse)(nil), // 5: cardwatcher.ListExpansionsResponse
	(*ListBlueprintsResponse)(nil), // 6: cardwatcher.ListBlueprintsResponse
	(*SaveWatchResponse)(nil),      // 7: cardwatcher.SaveWatchResponse
	(*ListWatchesResponse)(nil),    // 8: cardwatcher.ListWatchesResponse
}
var file_cardwatcher_service_proto_depIdxs = []int32{
	0, // 0: cardwatcher.CardWatcher.ListExpansions:input_type -> cardwatcher.ListExpansionsRequest
	1, // 1: cardwatcher.CardWatcher.ListBlueprints:input_type -> cardwatcher.ListBlueprintsRequest
	2, // 2: cardwatcher.CardWatcher.SaveWatch:input_type -> cardwatcher.SaveWatchRequest
	3, // 3: cardwatcher.CardWatcher.ListWatches:input_type -> google.protobuf.Empty
	4, // 4: cardwatcher.CardWatcher.DeleteWatchByID:input_type -> cardwatcher.DeleteWatchByIDRequest
	5, // 5: cardwatcher.CardWatcher.ListExpansions:output_type -> cardwatcher.ListExpansionsResponse
	6, // 6: cardwatcher.CardWatcher.ListBlueprints:output_type -> cardwatcher.ListBlueprintsResponse
	7, // 7: cardwatcher.CardWatcher.SaveWatch:output_type -> cardwatcher.SaveWatchResponse
	8, // 8: cardwatcher.CardWatcher.ListWatches:output_type -> cardwatcher.ListWatchesResponse
	3, // 9: cardwatcher.CardWatcher.DeleteWatchByID:output_type -> google.protobuf.Empty
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cardwatcher_service_proto_init() }
func file_cardwatcher_service_proto_init() {
	if File_cardwatcher_service_proto != nil {
		return
	}
	file_cardwatcher_requests_proto_init()
	file_cardwatcher_responses_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cardwatcher_service_proto_rawDesc), len(file_cardwatcher_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cardwatcher_service_proto_goTypes,
		DependencyIndexes: file_cardwatcher_service_proto_depIdxs,
	}.Build()
	File_cardwatcher_service_proto = out.File
	file_cardwatcher_service_proto_goTypes = nil
	file_cardwatcher_service_proto_depIdxs = nil
}
