// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: cardwatcher/service.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_cardwatcher_service_proto protoreflect.FileDescriptor

const file_cardwatcher_service_proto_rawDesc = "" +
	"\n" +
	"\x19cardwatcher/service.proto\x12\vcardwatcher\x1a\x1acardwatcher/requests.proto\x1a\x1bcardwatcher/responses.proto\x1a\x1bgoogle/protobuf/empty.proto2Y\n" +
	"\vCardWatcher\x12J\n" +
	"\tSaveWatch\x12\x1d.cardwatcher.SaveWatchRequest\x1a\x1e.cardwatcher.SaveWatchResponseB\x11Z\x0finternal/modelsb\x06proto3"

var file_cardwatcher_service_proto_goTypes = []any{
	(*SaveWatchRequest)(nil),  // 0: cardwatcher.SaveWatchRequest
	(*SaveWatchResponse)(nil), // 1: cardwatcher.SaveWatchResponse
}
var file_cardwatcher_service_proto_depIdxs = []int32{
	0, // 0: cardwatcher.CardWatcher.SaveWatch:input_type -> cardwatcher.SaveWatchRequest
	1, // 1: cardwatcher.CardWatcher.SaveWatch:output_type -> cardwatcher.SaveWatchResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cardwatcher_service_proto_init() }
func file_cardwatcher_service_proto_init() {
	if File_cardwatcher_service_proto != nil {
		return
	}
	file_cardwatcher_requests_proto_init()
	file_cardwatcher_responses_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cardwatcher_service_proto_rawDesc), len(file_cardwatcher_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cardwatcher_service_proto_goTypes,
		DependencyIndexes: file_cardwatcher_service_proto_depIdxs,
	}.Build()
	File_cardwatcher_service_proto = out.File
	file_cardwatcher_service_proto_goTypes = nil
	file_cardwatcher_service_proto_depIdxs = nil
}
