// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cardtrader

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCardtraderAdapter creates a new instance of MockCardtraderAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCardtraderAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCardtraderAdapter {
	mock := &MockCardtraderAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCardtraderAdapter is an autogenerated mock type for the CardtraderAdapter type
type MockCardtraderAdapter struct {
	mock.Mock
}

type MockCardtraderAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCardtraderAdapter) EXPECT() *MockCardtraderAdapter_Expecter {
	return &MockCardtraderAdapter_Expecter{mock: &_m.Mock}
}

// GetBlueprintNameByExpansionID provides a mock function for the type MockCardtraderAdapter
func (_mock *MockCardtraderAdapter) GetBlueprintNameByExpansionID(ctx context.Context, expansionID uint64, blueprintID uint64) (string, error) {
	ret := _mock.Called(ctx, expansionID, blueprintID)

	if len(ret) == 0 {
		panic("no return value specified for GetBlueprintNameByExpansionID")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64) (string, error)); ok {
		return returnFunc(ctx, expansionID, blueprintID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64) string); ok {
		r0 = returnFunc(ctx, expansionID, blueprintID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, uint64) error); ok {
		r1 = returnFunc(ctx, expansionID, blueprintID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCardtraderAdapter_GetBlueprintNameByExpansionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlueprintNameByExpansionID'
type MockCardtraderAdapter_GetBlueprintNameByExpansionID_Call struct {
	*mock.Call
}

// GetBlueprintNameByExpansionID is a helper method to define mock.On call
//   - ctx context.Context
//   - expansionID uint64
//   - blueprintID uint64
func (_e *MockCardtraderAdapter_Expecter) GetBlueprintNameByExpansionID(ctx interface{}, expansionID interface{}, blueprintID interface{}) *MockCardtraderAdapter_GetBlueprintNameByExpansionID_Call {
	return &MockCardtraderAdapter_GetBlueprintNameByExpansionID_Call{Call: _e.mock.On("GetBlueprintNameByExpansionID", ctx, expansionID, blueprintID)}
}

func (_c *MockCardtraderAdapter_GetBlueprintNameByExpansionID_Call) Run(run func(ctx context.Context, expansionID uint64, blueprintID uint64)) *MockCardtraderAdapter_GetBlueprintNameByExpansionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCardtraderAdapter_GetBlueprintNameByExpansionID_Call) Return(s string, err error) *MockCardtraderAdapter_GetBlueprintNameByExpansionID_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockCardtraderAdapter_GetBlueprintNameByExpansionID_Call) RunAndReturn(run func(ctx context.Context, expansionID uint64, blueprintID uint64) (string, error)) *MockCardtraderAdapter_GetBlueprintNameByExpansionID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlueprints provides a mock function for the type MockCardtraderAdapter
func (_mock *MockCardtraderAdapter) GetBlueprints(ctx context.Context, expansionID uint64) ([]*Blueprint, error) {
	ret := _mock.Called(ctx, expansionID)

	if len(ret) == 0 {
		panic("no return value specified for GetBlueprints")
	}

	var r0 []*Blueprint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) ([]*Blueprint, error)); ok {
		return returnFunc(ctx, expansionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) []*Blueprint); ok {
		r0 = returnFunc(ctx, expansionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*Blueprint)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, expansionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCardtraderAdapter_GetBlueprints_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlueprints'
type MockCardtraderAdapter_GetBlueprints_Call struct {
	*mock.Call
}

// GetBlueprints is a helper method to define mock.On call
//   - ctx context.Context
//   - expansionID uint64
func (_e *MockCardtraderAdapter_Expecter) GetBlueprints(ctx interface{}, expansionID interface{}) *MockCardtraderAdapter_GetBlueprints_Call {
	return &MockCardtraderAdapter_GetBlueprints_Call{Call: _e.mock.On("GetBlueprints", ctx, expansionID)}
}

func (_c *MockCardtraderAdapter_GetBlueprints_Call) Run(run func(ctx context.Context, expansionID uint64)) *MockCardtraderAdapter_GetBlueprints_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCardtraderAdapter_GetBlueprints_Call) Return(blueprints []*Blueprint, err error) *MockCardtraderAdapter_GetBlueprints_Call {
	_c.Call.Return(blueprints, err)
	return _c
}

func (_c *MockCardtraderAdapter_GetBlueprints_Call) RunAndReturn(run func(ctx context.Context, expansionID uint64) ([]*Blueprint, error)) *MockCardtraderAdapter_GetBlueprints_Call {
	_c.Call.Return(run)
	return _c
}

// GetExpansionNameByID provides a mock function for the type MockCardtraderAdapter
func (_mock *MockCardtraderAdapter) GetExpansionNameByID(ctx context.Context, expansionID uint64) (string, error) {
	ret := _mock.Called(ctx, expansionID)

	if len(ret) == 0 {
		panic("no return value specified for GetExpansionNameByID")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (string, error)); ok {
		return returnFunc(ctx, expansionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) string); ok {
		r0 = returnFunc(ctx, expansionID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, expansionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCardtraderAdapter_GetExpansionNameByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExpansionNameByID'
type MockCardtraderAdapter_GetExpansionNameByID_Call struct {
	*mock.Call
}

// GetExpansionNameByID is a helper method to define mock.On call
//   - ctx context.Context
//   - expansionID uint64
func (_e *MockCardtraderAdapter_Expecter) GetExpansionNameByID(ctx interface{}, expansionID interface{}) *MockCardtraderAdapter_GetExpansionNameByID_Call {
	return &MockCardtraderAdapter_GetExpansionNameByID_Call{Call: _e.mock.On("GetExpansionNameByID", ctx, expansionID)}
}

func (_c *MockCardtraderAdapter_GetExpansionNameByID_Call) Run(run func(ctx context.Context, expansionID uint64)) *MockCardtraderAdapter_GetExpansionNameByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCardtraderAdapter_GetExpansionNameByID_Call) Return(s string, err error) *MockCardtraderAdapter_GetExpansionNameByID_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockCardtraderAdapter_GetExpansionNameByID_Call) RunAndReturn(run func(ctx context.Context, expansionID uint64) (string, error)) *MockCardtraderAdapter_GetExpansionNameByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetExpansions provides a mock function for the type MockCardtraderAdapter
func (_mock *MockCardtraderAdapter) GetExpansions(ctx context.Context) ([]*Expansion, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetExpansions")
	}

	var r0 []*Expansion
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*Expansion, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*Expansion); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*Expansion)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCardtraderAdapter_GetExpansions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExpansions'
type MockCardtraderAdapter_GetExpansions_Call struct {
	*mock.Call
}

// GetExpansions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCardtraderAdapter_Expecter) GetExpansions(ctx interface{}) *MockCardtraderAdapter_GetExpansions_Call {
	return &MockCardtraderAdapter_GetExpansions_Call{Call: _e.mock.On("GetExpansions", ctx)}
}

func (_c *MockCardtraderAdapter_GetExpansions_Call) Run(run func(ctx context.Context)) *MockCardtraderAdapter_GetExpansions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCardtraderAdapter_GetExpansions_Call) Return(expansions []*Expansion, err error) *MockCardtraderAdapter_GetExpansions_Call {
	_c.Call.Return(expansions, err)
	return _c
}

func (_c *MockCardtraderAdapter_GetExpansions_Call) RunAndReturn(run func(ctx context.Context) ([]*Expansion, error)) *MockCardtraderAdapter_GetExpansions_Call {
	_c.Call.Return(run)
	return _c
}

// GetGames provides a mock function for the type MockCardtraderAdapter
func (_mock *MockCardtraderAdapter) GetGames(ctx context.Context) ([]*game, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetGames")
	}

	var r0 []*game
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*game, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*game); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*game)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCardtraderAdapter_GetGames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGames'
type MockCardtraderAdapter_GetGames_Call struct {
	*mock.Call
}

// GetGames is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCardtraderAdapter_Expecter) GetGames(ctx interface{}) *MockCardtraderAdapter_GetGames_Call {
	return &MockCardtraderAdapter_GetGames_Call{Call: _e.mock.On("GetGames", ctx)}
}

func (_c *MockCardtraderAdapter_GetGames_Call) Run(run func(ctx context.Context)) *MockCardtraderAdapter_GetGames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCardtraderAdapter_GetGames_Call) Return(gameMoqParams []*game, err error) *MockCardtraderAdapter_GetGames_Call {
	_c.Call.Return(gameMoqParams, err)
	return _c
}

func (_c *MockCardtraderAdapter_GetGames_Call) RunAndReturn(run func(ctx context.Context) ([]*game, error)) *MockCardtraderAdapter_GetGames_Call {
	_c.Call.Return(run)
	return _c
}

// GetProducts provides a mock function for the type MockCardtraderAdapter
func (_mock *MockCardtraderAdapter) GetProducts(ctx context.Context, blueprintID uint64, foil bool) ([]Product, error) {
	ret := _mock.Called(ctx, blueprintID, foil)

	if len(ret) == 0 {
		panic("no return value specified for GetProducts")
	}

	var r0 []Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, bool) ([]Product, error)); ok {
		return returnFunc(ctx, blueprintID, foil)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, bool) []Product); ok {
		r0 = returnFunc(ctx, blueprintID, foil)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, bool) error); ok {
		r1 = returnFunc(ctx, blueprintID, foil)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCardtraderAdapter_GetProducts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProducts'
type MockCardtraderAdapter_GetProducts_Call struct {
	*mock.Call
}

// GetProducts is a helper method to define mock.On call
//   - ctx context.Context
//   - blueprintID uint64
//   - foil bool
func (_e *MockCardtraderAdapter_Expecter) GetProducts(ctx interface{}, blueprintID interface{}, foil interface{}) *MockCardtraderAdapter_GetProducts_Call {
	return &MockCardtraderAdapter_GetProducts_Call{Call: _e.mock.On("GetProducts", ctx, blueprintID, foil)}
}

func (_c *MockCardtraderAdapter_GetProducts_Call) Run(run func(ctx context.Context, blueprintID uint64, foil bool)) *MockCardtraderAdapter_GetProducts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCardtraderAdapter_GetProducts_Call) Return(products []Product, err error) *MockCardtraderAdapter_GetProducts_Call {
	_c.Call.Return(products, err)
	return _c
}

func (_c *MockCardtraderAdapter_GetProducts_Call) RunAndReturn(run func(ctx context.Context, blueprintID uint64, foil bool) ([]Product, error)) *MockCardtraderAdapter_GetProducts_Call {
	_c.Call.Return(run)
	return _c
}

// Health provides a mock function for the type MockCardtraderAdapter
func (_mock *MockCardtraderAdapter) Health(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Health")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCardtraderAdapter_Health_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Health'
type MockCardtraderAdapter_Health_Call struct {
	*mock.Call
}

// Health is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCardtraderAdapter_Expecter) Health(ctx interface{}) *MockCardtraderAdapter_Health_Call {
	return &MockCardtraderAdapter_Health_Call{Call: _e.mock.On("Health", ctx)}
}

func (_c *MockCardtraderAdapter_Health_Call) Run(run func(ctx context.Context)) *MockCardtraderAdapter_Health_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCardtraderAdapter_Health_Call) Return(err error) *MockCardtraderAdapter_Health_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCardtraderAdapter_Health_Call) RunAndReturn(run func(ctx context.Context) error) *MockCardtraderAdapter_Health_Call {
	_c.Call.Return(run)
	return _c
}
