// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ntfy

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockNtfyAdapter creates a new instance of MockNtfyAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNtfyAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNtfyAdapter {
	mock := &MockNtfyAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNtfyAdapter is an autogenerated mock type for the NtfyAdapter type
type MockNtfyAdapter struct {
	mock.Mock
}

type MockNtfyAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNtfyAdapter) EXPECT() *MockNtfyAdapter_Expecter {
	return &MockNtfyAdapter_Expecter{mock: &_m.Mock}
}

// Notify provides a mock function for the type MockNtfyAdapter
func (_mock *MockNtfyAdapter) Notify(ctx context.Context, message string) error {
	ret := _mock.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for Notify")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNtfyAdapter_Notify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Notify'
type MockNtfyAdapter_Notify_Call struct {
	*mock.Call
}

// Notify is a helper method to define mock.On call
//   - ctx context.Context
//   - message string
func (_e *MockNtfyAdapter_Expecter) Notify(ctx interface{}, message interface{}) *MockNtfyAdapter_Notify_Call {
	return &MockNtfyAdapter_Notify_Call{Call: _e.mock.On("Notify", ctx, message)}
}

func (_c *MockNtfyAdapter_Notify_Call) Run(run func(ctx context.Context, message string)) *MockNtfyAdapter_Notify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNtfyAdapter_Notify_Call) Return(err error) *MockNtfyAdapter_Notify_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNtfyAdapter_Notify_Call) RunAndReturn(run func(ctx context.Context, message string) error) *MockNtfyAdapter_Notify_Call {
	_c.Call.Return(run)
	return _c
}
